# Deepchecks tutorial
[Deepchecks](https://docs.deepchecks.com/stable/getting-started/welcome.html) is a Python library for validating ML data and models. In the example below, you'll see how to use Deepchecks to evaluate a trained model, for example before deploying the model to production. 

For tabular data we are using here, Deepchecks can automatically segment the variables into bins, and evaluate the performance of the model in each bin, and highlight problems.


# Example scenario for wine quality dataset
Perhaps you are a large-scale wine producer, and for each batch of wine you produce, a tasting team evaluates a small sample of the wines for quality control (test set), and you want to check does your prediction model trained on historical data (training set) agree with them.

Deepchecks can help you develop an automated test for this, and keep track which features your model has the most problems with.

For example, maybe for the newest batch, your model does not agree with the experts on the samples (wines) with the highest alcohol-by-volume, making you suspect something is wrong.

In [ ]:
# Loading the model
from utils.idk import load_model

# Loading the data

In [100]:
from deepchecks.tabular.datasets.regression import wine_quality
from deepchecks.tabular import Dataset
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Load model

train, test = wine_quality.load_data(as_train_test=True) # set to false to get one big chunk of data
target = 'quality'

train_data = train.data.drop(train.data[train.data['alcohol'] > train.data['alcohol'].quantile(0.50)].index)
target_train = train_data[target]
train_data = train_data.drop(target, axis=1)
X_train = train_data
y_train = target_train

test_data = test.data.drop(target, axis=1)
y_test = test.data[target]
X_test = test_data

#X_train, X_test, y_train, y_test = train_test_split(
#    train_data, target_train, test_size=0.2, random_state=42
#)

train_ds = Dataset(X_train, label=y_train, cat_features=[])
test_ds  = Dataset(X_test,  label=y_test,  cat_features=[])

X_train['alcohol']
#train_data.nlargest(10, 'pH') # Get top 10 rows with largest pH (or any other column)
X_train.nlargest(10, 'alcohol') # Get top 10 rows with largest pH (or any other column)

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
158,795,10.8,0.890,0.30,2.6,0.132,7.0,60.0,0.99786,2.99,1.18,10.2
178,511,10.0,0.590,0.31,2.2,0.090,26.0,62.0,0.99940,3.18,0.63,10.2
183,1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
197,675,9.3,0.410,0.39,2.2,0.064,12.0,31.0,0.99840,3.26,0.65,10.2
211,1345,8.2,0.440,0.24,2.3,0.063,10.0,28.0,0.99613,3.25,0.53,10.2
320,1289,7.0,0.600,0.30,4.5,0.068,20.0,110.0,0.99914,3.30,1.17,10.2
337,508,10.0,0.590,0.31,2.2,0.090,26.0,62.0,0.99940,3.18,0.63,10.2
358,926,9.4,0.240,0.33,2.3,0.061,52.0,73.0,0.99786,3.47,0.90,10.2
382,1075,9.1,0.250,0.34,2.0,0.071,45.0,67.0,0.99769,3.44,0.86,10.2
386,1288,7.0,0.600,0.30,4.5,0.068,20.0,110.0,0.99914,3.30,1.17,10.2

In [99]:

from deepchecks.tabular.datasets.regression import wine_quality
from deepchecks.tabular import Dataset
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Load model

train = wine_quality.load_data(as_train_test=False)
target = 'quality'

train_data = train.data.drop(target, axis=1)
target_train = train.data[target]

X_train, X_test, y_train, y_test = train_test_split(
    train_data, target_train, test_size=0.2, random_state=42
)

train_ds = Dataset(X_train, label=y_train, cat_features=[])
test_ds  = Dataset(X_test,  label=y_test,  cat_features=[])

train= wine_quality.load_data(as_train_test=False)
train_data['alcohol']
train_data.nlargest(10, 'pH') # Get top 10 rows with largest pH (or any other column)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1316,5.4,0.740,0.00,1.20,0.041,16.0,46.0,0.99258,4.01,0.59,12.5
1321,5.0,0.740,0.00,1.20,0.041,16.0,46.0,0.99258,4.01,0.59,12.5
45,4.6,0.520,0.15,2.10,0.054,8.0,65.0,0.99340,3.90,0.56,13.1
695,5.1,0.470,0.02,1.30,0.034,18.0,44.0,0.99210,3.90,0.62,12.8
95,4.7,0.600,0.17,2.30,0.058,17.0,106.0,0.99320,3.85,0.60,12.9
1111,5.4,0.420,0.27,2.00,0.092,23.0,55.0,0.99471,3.78,0.64,12.3
1300,5.2,0.645,0.00,2.15,0.080,15.0,28.0,0.99444,3.78,0.61,12.5
94,5.0,1.020,0.04,1.40,0.045,41.0,85.0,0.99380,3.75,0.48,10.5
553,5.0,1.040,0.24,1.60,0.050,32.0,96.0,0.99340,3.74,0.62,11.5
588,5.0,0.420,0.24,2.00,0.060,19.0,50.0,0.99170,3.72,0.74,14.0

# Let's load the best model from tutorial 1 
Open MLFlow and find the hash of the best model you trained on the previous step, and try it on the data

In [101]:
#model = MLFlowModel.load(model_uri="models:/<model_name>/<stage_or_version>")
model = RandomForestRegressor(n_estimators=20, max_depth=3, random_state=0).fit(X_train, y_train)

# Let's check the results 
We will run some automatic checks for tabular data on our model

In [ ]:
# 2) baseline evaluation

from deepchecks.tabular.checks import WeakSegmentsPerformance
eval_result = WeakSegmentsPerformance()
result = eval_result.run(test_ds, model=model)
result.show()

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_conditions',
 '_conditions_index',
 '_create_heatmap_display',
 '_find_weak_segment',
 '_format_partition_vec_for_display',
 '_generate_check_result_value',
 '_prepare_config',
 '_target_encode_categorical_features_fill_na',
 '_weak_segments_search',
 'add_condition',
 'add_condition_segments_relative_performance_greater_than',
 'alternative_scorer',
 'categorical_aggregation_threshold',
 'clean_conditions',
 'columns',
 'conditions_decision',
 'config',
 'context_type',
 'encoder_mapping',
 'from_config',
 'from_json',
 'ignore_columns',
 'loss_per_sample',
 'max_categories_weak_segment',
 'metadata',
 'min_category_size_ratio',
 'multiple_segments_per_feature',
 'n_samples',
 'n_to_show',
 'n_top_features',
 'name',
 'params',
 'random_state',
 'remove_condition',
 'run',
 'run_logic',
 'score_per_sample',
 'segment_minimum_size_ratio',
 'to_json']

In [105]:
# suite_result is what you got from suite.run(...)

AttributeError: 'CheckResult' object has no attribute 'get_not_passed_checks'

If you check for example the `alcohol vs chlorides`-tab, perhaps we should collect more data where 0.05<`chlorides`<=0.06, as the model is not performing very well on that area in testing?

# More checks
let's look at a wider set of evaluations

In [ ]:
from deepchecks.tabular.suites import model_evaluation
baseline_suite = model_evaluation().run(train_ds, test_ds, model)
baseline_suite.show()

In [114]:
failed_only = baseline_suite.get_not_passed_checks(fail_if_warning=False)  # FAIL only
failed_or_warn = baseline_suite.get_not_passed_checks(fail_if_warning=True)  # FAIL+WARN

n_failed = len(failed_only)
n_failed_or_warn = len(failed_or_warn)

n_not_ran = len(baseline_suite.get_not_ran_checks())

print(n_failed, n_failed_or_warn, n_not_ran)

print(failed_or_warn)

3 5 7
[Train Test Performance:   Dataset Class    Metric     Value  Number of samples
0   Train  <NA>  Neg RMSE -0.542528                670
1   Train  <NA>   Neg MAE -0.427153                670
2   Train  <NA>        R2  0.283631                670
3    Test  <NA>  Neg RMSE -0.722213                320
4    Test  <NA>   Neg MAE -0.567992                320
5    Test  <NA>        R2  0.196282                320, Prediction Drift: {'Drift score': 0.19430970149253735, 'Method': 'Kolmogorov-Smirnov', 'Samples per class': {5.1427719641885155: 28, 5.1752289699066605: 23, 5.373260462910617: 17, 5.192952470960824: 16, 5.175414584479836: 13, 5.092035790876043: 12, 5.225595091252144: 11, 5.20787159019798: 11, 5.230691635360392: 9, 5.337137237551799: 9, 5.28454137258077: 9, 5.147394196282907: 8, 5.114751575991586: 8, 5.695165136525786: 8, 5.54073205067059: 8, 5.10630245754271: 8, 5.099853738248277: 7, 5.3660725075925: 7, 5.1039669812051525: 7, 5.157038630855182: 7, 5.4881361856995605: 7, 5.248415136414555: 7, 5.473613716402452: 6, 5.124492796594188: 6, 5.15150743923978: 6, 5.425856327881645: 6, 5.183964444957924: 6, 5.2555893255860395: 6, 5.161408504220386: 6, 5.142838708344527: 6, 5.334714976729009: 6, 5.075946593008222: 5, 5.098822107970068: 5, 5.71883106203996: 5, 5.412480040504163: 5, 5.201687946012088: 5, 5.2345946707282796: 5, 5.128395831962076: 5, 5.546768777657677: 5, 5.29254090232541: 5, 5.441714629922032: 5, 5.1511270741354265: 5, 5.307602813258736: 5, 5.390996973213081: 5, 5.161214661969181: 5, 5.0640154026791135: 5, 5.781627164440399: 4, 5.333369496701573: 4, 5.189681251146503: 4, 5.331386800216862: 4, 5.519358293645082: 4, 5.170214241445317: 4, 5.930474976085718: 4, 5.0897670586944965: 4, 5.452111925751875: 4, 5.077835868365388: 4, 5.742014112452745: 4, 5.127874126445208: 4, 5.564397976184764: 4, 5.93169448828084: 3, 5.901132457416373: 3, 5.096845927277981: 3, 5.02521041969575: 3, 5.02373974730599: 3, 5.90044448828084: 3, 5.59481188303395: 3, 5.110672330907914: 3, 5.417001533112419: 3, 5.589825130379775: 3, 5.366330484841904: 3, 5.473955846897373: 3, 5.555557280344405: 3, 5.452221153019822: 3, 5.491440730613369: 3, 5.398004876309274: 3, 5.152653640339805: 3, 5.323433228290707: 3, 5.21675031411328: 3, 5.672007802841516: 3, 5.538665451267925: 3, 5.540714270916165: 3, 5.123487051042851: 3, 5.659040734611909: 3, 5.316448047565466: 3, 5.137307516729125: 3, 5.2604931629755205: 3, 5.194051124511707: 3, 5.402467165320069: 3, 5.40245488675578: 3, 5.899224976085718: 3, 5.1831574593533345: 3, 5.392912858337984: 2, 5.072926179166189: 2, 5.731636241202358: 2, 5.3888005386560724: 2, 5.18502568525702: 2, 5.438145262461519: 2, 5.5359842813104345: 2, 5.511978125432742: 2, 5.083025461591705: 2, 5.235972478870646: 2, 5.286110857616758: 2, 5.378560020080013: 2, 5.493709192183362: 2, 5.455412330607285: 2, 5.25744170200319: 2, 5.419378633334783: 2, 5.539123186038461: 2, 5.053230807892679: 2, 5.868503645802174: 2, 5.781253918145137: 2, 4.931171652528682: 2, 5.526054330669171: 2, 5.340257132187042: 2, 5.212501296308914: 2, 5.288133422051412: 2, 5.745502762526524: 2, 5.51231835579626: 2, 5.3575905550026395: 2, 5.716526584108075: 2, 5.704966892851592: 2, 5.986615326962911: 2, 5.27301152055131: 2, 5.626407584161007: 2, 5.533351882458249: 2, 5.66849578817502: 2, 5.4383121977760895: 2, 5.949562602086457: 2, 5.0718167545373785: 2, 5.703384910772073: 2, 5.3578625201910395: 2, 5.359850451936886: 2, 5.142216297648351: 2, 5.1844809081119845: 2, 6.009945978612148: 2, 5.039030885382024: 2, 5.477147024484836: 2, 4.996837510939532: 2, 4.987379706219957: 2, 5.577927530716409: 2, 5.382871591423554: 2, 5.312081245035499: 2, 5.875499949891169: 2, 5.474127556792914: 2, 5.145285193947663: 2, 5.381442167131476: 2, 5.34258893234422: 2, 5.198234629642247: 2, 5.568142534683185: 2, 5.106442913091398: 2, 3.892268409161191: 2, 5.524560423825962: 2, 5.115772140584022: 2, 5.50100674397244: 2, 5.411445492899725: 2, 5.317332965562278: 2, 5.367658769582517: 2, 5.426040711228681: 2, 5.513342354475066: 2, 5.159485116458318: 2, 5.241804729012937: 2, 5.267158473993123: 2, 5.079122426223817: 2, 5.300414857940621: 2, 5.4933304755768955: 2, 5.343031911115882: 2, 5.541132426922784: 2, 5.536572487775563: 2, 6.037291465173378: 2, 5.122673783410688: 2, 5.401451889045017: 2, 5.360017387251456: 2, 6.03169448828084: 2, 5.369530232948326: 2, 5.634266336326641: 2, 5.133403573081264: 2, 5.497279641916626: 2, 5.509870879577112: 2, 5.338706722587787: 2, 5.211774625565869: 2, 5.500623698187073: 2, 5.315096096441485: 2, 5.327179810305236: 2, 5.316908936348397: 2, 5.129018242658253: 2, 5.349776887662335: 2, 5.039222582144604: 2, 5.340417943225577: 2, 5.6665476556351235: 2, 5.356945576788638: 2, 5.987528614072646: 2, 5.895827731270684: 1, 5.277353417262654: 1, 5.2700019970503496: 1, 5.426740978592595: 1, 5.349474469866908: 1, 5.980474976085718: 1, 5.791845774405046: 1, 5.310250176239409: 1, 5.450224553840876: 1, 5.510895217484157: 1, 5.506364904718069: 1, 5.19220708272328: 1, 5.102101965854617: 1, 5.505503905595932: 1, 5.6065450116070705: 1, 5.6613507162781485: 1, 5.8955700863669644: 1, 5.032465497995017: 1, 5.734349411926079: 1, 6.097047243465806: 1, 5.4691733688695665: 1, 5.217233250423666: 1, 5.5534199927938195: 1, 5.537523093328703: 1, 5.949224976085718: 1, 5.32970400034819: 1, 5.086746644852464: 1, 5.4374173838625595: 1, 5.284640337991902: 1, 5.100946567363119: 1, 5.07828206934578: 1, 6.031262421546498: 1, 6.075466415765038: 1, 5.4876304565949585: 1, 5.9479571189428615: 1, 5.852295121336758: 1, 5.152210555290178: 1, 5.697475118192024: 1, 5.803369872925435: 1, 5.630031363649046: 1, 5.6026707185486595: 1, 5.558249455449266: 1, 5.493316910259691: 1, 5.71539045472324: 1, 5.058543522300311: 1, 5.501398691414828: 1, 5.5184274406587654: 1, 5.654089179235422: 1, 5.650073509675182: 1, 5.416577503898538: 1, 5.081391651638297: 1, 5.368919796138917: 1, 5.3913838384711825: 1, 5.504817017990851: 1, 5.218956360928645: 1, 5.512475506631971: 1, 5.30216880365303: 1, 5.264737100591249: 1, 5.170377141393969: 1, 5.290765890136646: 1, 5.27516632263254: 1, 5.226617243950182: 1, 5.086264355650751: 1, 5.584522053681904: 1, 5.213456089262987: 1, 5.1908162999263725: 1, 6.015158006526762: 1, 5.181246873579811: 1, 5.423288728626081: 1, 5.336106202496882: 1, 5.454874185024503: 1, 5.307729992253487: 1, 5.729203995805663: 1, 5.2807292070656935: 1, 5.381093408294562: 1, 5.308631198731023: 1, 5.450632460270904: 1, 5.384416117898164: 1, 5.408872110236993: 1, 5.234215568560531: 1, 5.262747912444847: 1, 5.155209742338743: 1, 5.110621737520742: 1, 5.277153919227773: 1, 5.231894580906211: 1, 5.3911224039742915: 1, 5.046936733134857: 1, 5.402568874991893: 1, 5.098702214475709: 1, 5.734699472054238: 1, 5.285011610255346: 1, 5.24996747056088: 1, 5.8842386120226875: 1, 5.330936389971339: 1, 5.002715564287224: 1, 5.455844689326734: 1, 5.23941024502925: 1, 5.346172203544081: 1, 5.3008652681861435: 1, 5.337236202962931: 1, 5.323269539672575: 1, 5.028814134287882: 1, 5.489508573697738: 1, 5.3341555779758085: 1, 5.351886705885109: 1, 5.3212212502562135: 1, 5.461008937824566: 1, 5.36938771009674: 1, 5.048085934657595: 1, 5.121378048707607: 1, 5.062141584379755: 1, 5.344527593766729: 1, 5.0591536252604605: 1, 5.154284773423798: 1, 5.1865172073837265: 1, 5.305687854663258: 1, 5.222570457661511: 1, 5.3890908779425875: 1, 5.426255891387789: 1, 5.141332062527939: 1, 5.410145926595876: 1, 5.201148812773571: 1, 5.546993981677088: 1, 5.230148747630733: 1, 5.525963626027798: 1, 5.278627236652654: 1, 5.792839028874661: 1, 5.201423232042236: 1, 5.87430773423539: 1, 5.389118764951004: 1, 5.142139048132528: 1, 4.693790696146112: 1, 4.312600684829929: 1, 5.323760950174317: 1, 5.3796637113878925: 1, 5.322524289598144: 1, 4.815689503869993: 1, 5.30187245704397: 1, 6.063960813524142: 1, 5.840088071323814: 1, 5.897234643768719: 1, 5.179132005274549: 1, 5.39441435627626: 1, 5.3931961584625: 1, 5.597160391826042: 1, 5.287968881142375: 1, 5.370084578245237: 1, 5.554968739297346: 1, 5.409541441759667: 1, 6.120101164401335: 1, 5.358622121969065: 1, 5.493035462744643: 1, 5.435774770047024: 1, 5.367331047698906: 1, 5.47499434764057: 1, 5.5410929875226325: 1, 5.263167615555262: 1, 5.765949472054238: 1, 5.582666299971685: 1, 5.311539314120974: 1, 5.404219520149768: 1, 5.337474201417341: 1, 5.388467618149419: 1, 5.412446316907914: 1, 5.462123646541885: 1, 5.3387173551673035: 1, 5.561273811284268: 1, 5.37905821805734: 1, 5.355148816809631: 1, 5.251797818306863: 1, 5.348156475922817: 1, 5.145428442811697: 1, 5.125184691033624: 1, 5.650860004099378: 1, 5.361261771821778: 1, 5.170143979271651: 1, 5.120263378777673: 1, 5.001646372886624: 1, 5.738847011003277: 1, 5.560075744317066: 1, 5.265391365542966: 1, 5.583741669831241: 1, 4.9593593180230275: 1, 5.1464801990754125: 1, 5.417287621469132: 1, 5.5385380571146: 1, 5.493606609746078: 1, 5.26677175971524: 1, 5.246094851810295: 1, 5.3203591427045085: 1, 5.4666837383337405: 1, 5.512114569779927: 1, 5.333884136110672: 1, 5.284724053490967: 1, 4.920554335039664: 1, 5.324568757523011: 1, 5.4361545009450385: 1, 5.957069523109671: 1, 4.981591912065659: 1, 5.402676244447352: 1, 5.414386135774658: 1, 5.491054557711401: 1, 5.562088027941674: 1, 5.105200450529111: 1, 5.5865318349493345: 1, 5.551155893310538: 1, 5.11600144820065: 1, 5.315062904611488: 1, 5.313341219703501: 1, 5.512036560532226: 1, 5.674845087905359: 1, 5.415788113301768: 1, 5.5697499078134465: 1, 5.5586874811200735: 1, 5.828476140367359: 1, 5.304405845258517: 1, 5.119583107394989: 1, 5.617095441927111: 1, 5.747475118192024: 1, 5.632557011800158: 1, 5.346669590985537: 1, 4.981554288437275: 1, 5.482580275033065: 1, 5.374297679494652: 1, 5.751305487402979: 1, 5.894350574171844: 1, 5.56133276476034: 1, 5.212218803874662: 1, 5.364218866421721: 1, 5.722252384841235: 1, 5.839687380393491: 1, 5.6592501038460465: 1, 5.3011602810183955: 1, 5.748841367892083: 1, 5.610862981854351: 1, 5.188541906235278: 1, 5.903077007390179: 1, 5.48709228666098: 1, 5.25891903668696: 1, 5.315336334280028: 1, 5.300000993678163: 1, 5.380923960869007: 1, 5.441285037107876: 1, 5.046665420505672: 1, 5.354282482205035: 1, 5.404482570856137: 1, 5.3608131484563515: 1, 5.40349736343841: 1, 5.316081584354459: 1, 5.273136920482287: 1, 5.4237973143281: 1, 5.335114202902748: 1, 5.685254294538296: 1, 5.502649758682926: 1, 5.650425068840009: 1, 5.018645032308743: 1, 5.590799420857635: 1, 5.251881533805928: 1, 5.019836711938102: 1, 5.222731033717927: 1, 5.652704182762397: 1, 5.273185242968343: 1, 5.493455197837262: 1, 5.504680573643664: 1, 5.4835193124527315: 1, 5.774971412917153: 1, 5.268131664648108: 1, 5.203127284071789: 1, 5.547978428695174: 1, 5.432976418786498: 1, 5.843531926345161: 1, 5.608752822347369: 1, 5.489929928755297: 1}}, Regression Error Distribution - Test Dataset: {'Mean Prediction Error': 0.23452345135452496, 'Median Prediction Error': 0.25976119545277987, 'Kurtosis Value': 0.9418675579788398, 'RMSE': 0.7222134751412141}, Weak Segments Performance - Train Dataset: {'weak_segments_list':    Neg RMSE Score              Feature1               Feature1 Range  \
0        -0.86357             sulphates    (0.6050000190734863, inf)
1       -0.847001               alcohol     (9.849999904632568, inf)
2       -0.819999               alcohol     (9.849999904632568, inf)
3       -0.796054         fixed acidity     (9.949999809265137, inf)
4       -0.793433               alcohol     (9.849999904632568, inf)
5       -0.789876  total sulfur dioxide                 (-inf, 69.5)
6       -0.774254      volatile acidity   (-inf, 0.5049999952316284)
7        -0.76435  total sulfur dioxide                 (-inf, 69.5)
14      -0.756808             chlorides  (-inf, 0.06350000202655792)
15      -0.756472  total sulfur dioxide                 (-inf, 69.5)
16      -0.731187               alcohol     (9.849999904632568, inf)
17      -0.730661      volatile acidity    (0.7524999976158142, inf)
21      -0.725122        residual sugar    (-inf, 1.550000011920929)
22      -0.708778  total sulfur dioxide                 (-inf, 69.5)
23      -0.690337            Unnamed: 0                (1402.0, inf)
29      -0.652234               alcohol     (9.849999904632568, inf)
30      -0.595799             sulphates    (0.5949999988079071, inf)
37      -0.587076  total sulfur dioxide                 (-inf, 69.5)

                Feature2                           Feature2 Range % of Data  \
0                alcohol  (9.849999904632568, 10.016666889190674)      7.46
1         residual sugar               (-inf, 1.8499999642372131)      5.52
2    free sulfur dioxide                              (-inf, 7.5)      5.97
3             Unnamed: 0                          (514.5, 1402.0)      5.82
4              chlorides               (0.09349999949336052, inf)      5.67
5              chlorides               (0.13750000298023224, inf)      5.67
6                alcohol                 (9.849999904632568, inf)      9.85
7             Unnamed: 0                            (1398.0, inf)      7.01
14                                                           None      5.37
15   free sulfur dioxide                              (25.5, inf)      6.27
16            Unnamed: 0                             (575.5, inf)     15.52
17  total sulfur dioxide                             (-inf, 69.5)      7.76
21                                                           None      5.82
22               alcohol                 (9.849999904632568, inf)     20.15
23                                                           None      9.85
29                                                           None     25.22
30                                                           None      49.1
37                                                           None      70.6

                                   Samples in Segment
0   [1241, 1263, 228, 132, 286, 959, 866, 969, 392...
1   [1241, 228, 53, 132, 351, 286, 1185, 102, 969,...
2   [166, 892, 837, 123, 286, 74, 397, 866, 102, 4...
3   [1221, 152, 487, 837, 132, 588, 365, 392, 1009...
4   [166, 487, 837, 132, 351, 866, 112, 991, 784, ...
5   [1162, 193, 1042, 132, 935, 1272, 256, 866, 11...
6   [99, 487, 837, 1263, 228, 132, 343, 286, 866, ...
7   [1036, 228, 1268, 851, 286, 1186, 102, 579, 72...
14  [892, 879, 851, 286, 9, 211, 477, 1247, 1104, ...
15  [228, 132, 112, 669, 1160, 10, 950, 374, 174, ...
16  [166, 99, 487, 1241, 837, 1190, 228, 132, 851,...
17  [1193, 576, 1162, 235, 1272, 825, 1198, 547, 1...
21  [597, 115, 1268, 9, 102, 613, 1160, 10, 449, 9...
22  [166, 99, 892, 1241, 837, 1263, 1190, 228, 53,...
23  [1036, 228, 1143, 1268, 851, 286, 1186, 102, 5...
29  [166, 99, 892, 487, 1241, 837, 1263, 1190, 228...
30  [535, 166, 152, 400, 1193, 308, 214, 1162, 684...
37  [311, 895, 1221, 535, 597, 979, 166, 152, 115,...  , 'avg_score': -0.543}, Weak Segments Performance - Test Dataset: {'weak_segments_list':    Neg RMSE Score              Feature1  \
0       -1.385702  total sulfur dioxide
1       -1.335736               alcohol
9       -1.308643               alcohol
10       -1.24277               density
17      -1.237302        residual sugar
18      -1.214472      volatile acidity
19      -1.194723         fixed acidity
20      -1.194187             chlorides
21      -1.186458             chlorides
23      -1.180485             chlorides
24      -1.172422             sulphates
25      -1.156549               density
33      -1.145094      volatile acidity
35      -1.141469             sulphates
36      -1.127444             sulphates
37      -1.073768         fixed acidity
38      -1.059133            Unnamed: 0
39      -1.057965  total sulfur dioxide
40      -1.053045             sulphates
41      -1.031289  total sulfur dioxide
42      -1.004627             sulphates
43      -0.995151         fixed acidity
44      -0.974185  total sulfur dioxide

                              Feature1 Range             Feature2  \
0                                (36.0, inf)            chlorides
1                  (12.150000095367432, inf)
9                  (11.550000190734863, inf)           Unnamed: 0
10                (-inf, 0.9947700202465057)            chlorides
17                  (4.849999904632568, inf)
18                 (0.5849999785423279, inf)            chlorides
19                (-inf, 7.6000001430511475)            chlorides
20                            (-inf, 0.0625)           Unnamed: 0
21                            (-inf, 0.0625)  free sulfur dioxide
23               (-inf, 0.05550000071525574)
24  (0.6850000023841858, 0.8650000095367432)           Unnamed: 0
25                (-inf, 0.9940199851989746)
33                 (0.8449999988079071, inf)
35               (0.8149999976158142, 0.875)
36   (0.7549999952316284, 0.824999988079071)  free sulfur dioxide
37                              (-inf, 6.75)           Unnamed: 0
38                            (277.0, 458.5)  free sulfur dioxide
39                               (46.5, inf)        fixed acidity
40                 (0.6850000023841858, inf)        fixed acidity
41                              (-inf, 19.5)           Unnamed: 0
42                 (0.7199999988079071, inf)     volatile acidity
43                              (-inf, 6.75)  free sulfur dioxide
44                              (-inf, 13.5)  free sulfur dioxide

                 Feature2 Range % of Data  \
0                (-inf, 0.0625)       5.0
1                          None      5.62
9                 (-inf, 887.0)      6.88
10               (-inf, 0.0625)      5.62
17                         None       5.0
18               (-inf, 0.0625)       5.0
19               (-inf, 0.0625)      7.19
20               (-inf, 1127.5)      6.25
21                  (11.5, inf)      7.81
23                         None      6.56
24                (-inf, 461.0)      6.88
25                         None      6.25
33                         None       5.0
35                         None       5.0
36                 (-inf, 13.5)      5.62
37                (-inf, 992.5)      6.25
38                 (-inf, 13.5)      8.44
39                 (-inf, 6.75)      6.25
40    (-inf, 7.049999952316284)       5.0
41                (-inf, 515.0)      5.62
42  (-inf, 0.33500000834465027)       7.5
43                 (-inf, 12.5)      5.94
44                  (-inf, 5.5)       5.0

                                   Samples in Segment
0   [76, 211, 5, 185, 60, 155, 117, 265, 95, 136, ...
1   [244, 76, 119, 185, 60, 317, 220, 164, 155, 15...
9   [76, 119, 211, 213, 157, 109, 218, 220, 247, 1...
10  [76, 211, 5, 193, 185, 60, 312, 288, 155, 117,...
17  [90, 59, 196, 10, 301, 265, 133, 245, 250, 27,...
18  [230, 143, 5, 193, 256, 155, 117, 131, 95, 0, ...
19  [230, 76, 211, 5, 193, 281, 57, 185, 312, 288,...
20  [143, 76, 119, 211, 5, 185, 155, 117, 115, 265...
21  [230, 76, 119, 211, 5, 193, 281, 57, 185, 60, ...
23  [76, 119, 211, 5, 193, 57, 185, 268, 312, 155,...
24  [90, 76, 157, 45, 124, 59, 152, 72, 10, 86, 30...
25  [244, 76, 211, 5, 193, 185, 312, 247, 155, 117...
33  [297, 5, 165, 147, 19, 126, 256, 38, 155, 117,...
35  [90, 222, 46, 234, 79, 72, 304, 140, 155, 277,...
36  [45, 30, 66, 140, 155, 28, 266, 238, 26, 61, 1...
37  [76, 211, 5, 94, 204, 181, 184, 247, 164, 144,...
38  [157, 232, 109, 59, 315, 152, 86, 155, 199, 23...
39  [76, 211, 5, 185, 204, 247, 155, 267, 117, 83,...
40  [76, 222, 285, 210, 181, 152, 164, 155, 26, 10...
41  [109, 22, 184, 301, 175, 199, 277, 89, 141, 28...
42  [183, 84, 7, 46, 45, 109, 30, 304, 112, 2, 239...
43  [193, 185, 165, 147, 184, 19, 69, 144, 155, 83...
44  [33, 300, 262, 22, 68, 144, 208, 303, 141, 0, ...  , 'avg_score': -0.722}]

# Bonus feature engineering: 
you could try various ways to improve the model, for example, by 

1) reweighting some samples in training like here (not very effective)
2) tuning hyperparameters
3) trying other model types
4) feature engineering, like making a combination column (alcohol * sulphates)
5) Add a separate model just for that weak segment and blend the results

... Or just collect more data from that segment!

In [71]:
from sklearn.ensemble import RandomForestRegressor
import numpy as np

mask = (
    (X_train['alcohol'] >= 9.9) & (X_train['alcohol'] <= 10.2) &
    (X_train['chlorides'] > 0.11)
    #(X_train['chlorides'] > 0.11) & (X_train['chlorides'] <= 0.06)
)

weights = np.ones(len(X_train), float)
weights[mask] = 20.0

rw_model = RandomForestRegressor(n_estimators=20, max_depth=2, random_state=0)
rw_model.fit(X_train, y_train, sample_weight=weights)

RandomForestRegressor(max_depth=2, n_estimators=20, random_state=0)

In [73]:
# Using deprecated SegmentPerformance as it's the only way to show performance on specific pairs
from deepchecks.tabular.checks import SegmentPerformance
eval_result = SegmentPerformance(feature_1='alcohol', feature_2='chlorides').run(test_ds, model=rw_model)
eval_result.show()

/home/ubuntu/miniconda3/envs/mlops_eng/lib/python3.11/site-packages/deepchecks/tabular/checks/model_evaluation/segment_performance.py:72: DeprecationWarning:

The SegmentPerformance check is deprecated and will be removed in the 0.11 version. Please use the WeakSegmentsPerformance check instead.

VBox(children=(HTML(value='<h4><b>Segment Performance</b></h4>'), HTML(value='<p>Display performance score seg…

# Permanently delete MLflow experiments.
Even though you delete an MLflow experiment from the UI by clicking the rubbish bin button next to the experiment name, the experiment still exists in the PostgreSQL database used by MLflow. This will cause errors when you want to create an experiment or record runs under an experiment that has the same name as the experiment you deleted from the UI. To permanently delete an experiment, the following steps are required: 

Keep a note of the ID of the experiment you want to delete, then delete the experiment in the UI.

Shell into the pod where the MLflow server is running:
```bash
# first get the pod name
export mlflowpod="$(kubectl -n mlflow get pod -l app=mlflow | grep "mlflow-"|cut -d' ' -f1)"

# then shell into the pod
kubectl -n mlflow exec -it $mlflowpod -- bash
```
Now you should be inside the pod and see something like 
<img src="../images/shell-mlflow-pod.png">

Inside the pod, run the following command
```bash
mlflow gc --backend-store-uri postgresql://mlflow:KFSg-AYoiPdfRun64z2-w89Kk7z5cJL2IbVvSd3l8Og@postgres:5432/mlflowdb --experiment-ids <the-id-of-the-experiment-you-deleted-on-ui>
# The value given to --experiment-ids can be multiple experiment IDs separated by comma. If experiment-ids are not given, all experiments you deleted on the UI will be permanently deleted. For more info of mlflow gc, check https://mlflow.org/docs/2.9.2/cli.html?highlight=mlflow%20gc#mlflow-gc
```

If you have registered models corresponding to the MLflow runs under the deleted experiment, go back to the UI and delete them. You can delete all versions of a registered model:
<img src="../images/delete-all-versions-registered-model.png" />
or a single version of a registered model:
<img src="../images/delete-single-version-registered-model.png" />

#### How about permanently deleting MLflow runs?
Permanently deleting an MLflow run follows the similar steps: keep a note of the run ID -> delete the run from the UI -> shell into the mlflow pod -> run the following command
```bash
mlflow gc --backend-store-uri postgresql://mlflow:KFSg-AYoiPdfRun64z2-w89Kk7z5cJL2IbVvSd3l8Og@postgres:5432/mlflowdb --run-ids <your-deleted-run-id>
```
 -> clean the registered model version corresponding to the deleted run.

In [119]:
from mlflow.tracking import MlflowClient
c = MlflowClient()
r = c.get_run("1ac878599a5c4c7abcda81d68f94505d")
print(r.info.lifecycle_stage, r.info.status)

MlflowException: Run '1ac878599a5c4c7abcda81d68f94505d' not found